# Generated by Django 5.2 on 2025-12-25 10:02

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='游戏名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='游戏简介')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=config.utils.universal_upload_path, verbose_name='封面图')),
                ('game_file', models.FileField(upload_to=config.utils.universal_upload_path, verbose_name='游戏文件 (.html/.js)')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小游戏',
                'verbose_name_plural': '小游戏',
            },
        ),
    ]
