# Generated by Django 5.2 on 2025-12-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
            ],
            options={
                'verbose_name': '游戏分类',
                'verbose_name_plural': '游戏分类',
            },
        ),
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
            ],
            options={
                'verbose_name': '游戏标签',
                'verbose_name_plural': '游戏标签',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamecategory', verbose_name='游戏分类'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='game.gametag', verbose_name='游戏标签'),
        ),
    ]
