# Generated by Django 5.2 on 2025-12-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamecategory_gametag_game_category_game_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='gametag',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='URL别名'),
        ),
    ]
