# Generated by Django 5.2 on 2025-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_slug_alter_gamecategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
