# Generated by Django 5.2 on 2025-12-26 00:26

import config.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=config.utils.universal_upload_path, verbose_name='图片文件')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='图片名称')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小(KB)')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='宽')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='高')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '图片素材',
                'verbose_name_plural': '图片素材',
                'ordering': ['-created_at'],
            },
        ),
    ]
