# Generated by Django 5.2 on 2025-12-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='name',
            field=models.CharField(blank=True, help_text='留空，则使用文件名', max_length=255, verbose_name='图片名称'),
        ),
    ]
