# Generated by Django 5.2 on 2026-01-04 10:38

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='工具名称')),
                ('description', models.TextField(blank=True, verbose_name='工具简介')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=config.utils.universal_upload_path)),
                ('url_name', models.CharField(help_text='对应 urls.py中的name', max_length=100, verbose_name='URL 别名')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('password', models.CharField(blank=True, help_text='留空则无需密码', max_length=50, verbose_name='访问密码')),
            ],
            options={
                'verbose_name': '在线工具',
                'verbose_name_plural': '在线工具',
                'ordering': ['order'],
            },
        ),
    ]
